### ISSUE TITLE
Question about message length

### ISSUE THREAD

**Issue by jpeskar** [washo4evr/Socket.io-v1.x-Library#9]
I am refactoring the code to meet my application and as I am doing so I came across the message length. I have just started looking at what Wireshark sniffing, but I thought I would also go to the source. I'm confused on the message length in mask. Your comments say 128 due to the mask, for say the "52" to upgrade, but the mask is only 4 bytes long? I'm missing something really stupid and I know it.

**Comment by washo4evr** [comment]
"52" is the reply tou need to send (in websocket) to confirm that connection was properly upgraded

the mask is always 4 bytes long
the same 4 bytes are used to "encrypt" the message with a modulo
1st mask byte for 1st message byte
2nd mask byte for 2nd message byte
3rd mask byte for 3rd message byte
4th mask byte for 4th message byte
1st mask byte for 5th message byte
2nd mask byte for 6th message byte
and so on

128 because the text is masked
you add to 128 the size of the message
is you dont send 128, the server will expect a non masked message

**Comment by washo4evr** [comment]
Wireshark and I did become intimate after a few nights together ;)
in the end it was totally worth my time

thank you for using my library, I'm glad you like it

A big update is on its way

**Comment by washo4evr** [comment]
Did you try the new version?
You should be able to send message bigger than 256 chars now

**Comment by jpeskar** [comment]
Sorry. I have not had time lately. Work has been crazy and spring hit
leaving me with my spring cleanup.
